[package]
name = "r26_async-await"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.13.1", features = ["attributes"] }
futures = "0.3.31"
