[package]
name = "ch02-05-actix-gcd"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.11.0"
serde = { version = "1.0.219", features = ["derive"] }
