[package]
name = "ch14-01-release-profiles"
version = "0.1.0"
edition = "2024"

[dependencies]

# # 编译项目时配置优化级别
# # cargo build => dev [unoptimized + debuginfo]
# [profile.dev]
# opt-level = 0

# # cargo build --release => [optimized]
# [profile.release]
# opt-level = 3 # 0-3
